import React, { useState, useEffect } from 'react';
import DashboardLayout from '../components/DashboardLayout';
import { useAuth } from '../context/AuthContext';
import axios from 'axios';
import toast from 'react-hot-toast';
import {
  Layers,
  ChevronLeft,
  ChevronRight,
  RotateCcw,
  CheckCircle2,
  XCircle,
  Sparkles
} from 'lucide-react';

const Flashcards = () => {
  const { user } = useAuth();
  const [materials, setMaterials] = useState([]);
  const [selectedMaterial, setSelectedMaterial] = useState(null);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isFlipped, setIsFlipped] = useState(false);
  const [loading, setLoading] = useState(true);
  const [enrolledCourses, setEnrolledCourses] = useState([]);
  const [selectedCourse, setSelectedCourse] = useState('all');

  useEffect(() => {
    fetchMaterials();
    if (user?.role === 'student') fetchEnrolledCourses();
  }, []);

  const fetchEnrolledCourses = async () => {
    try {
      const res = await axios.get('/api/courses');
      setEnrolledCourses(res.data.filter(c => c.isEnrolled));
    } catch (err) {
      console.error(err);
    }
  };

  const fetchMaterials = async () => {
    try {
      const res = await axios.get('/api/materials');
      setMaterials(res.data.filter(m => m.flashcards && m.flashcards.length > 0));
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const getTeacherId = (teacher) => {
    if (!teacher) return null;
    if (typeof teacher === 'object') return teacher._id?.toString();
    return teacher.toString();
  };

  const getCourseLabel = (teacher) => {
    const id = getTeacherId(teacher);
    const course = enrolledCourses.find(c => c._id?.toString() === id);
    return course ? (course.subject || course.teacherName) : null;
  };

  const filteredMaterials = (user?.role === 'student' && selectedCourse !== 'all')
    ? materials.filter(m => getTeacherId(m.teacher) === selectedCourse)
    : materials;

  const handleRecord = (isCorrect) => {
    const card = selectedMaterial.flashcards[currentIndex];
    // Record attempt without blocking navigation
    axios.post('/api/attempts/record', {
      materialId: selectedMaterial._id,
      type: 'flashcard',
      concept: card.concept || card.front,
      isCorrect
    }).catch(err => {
      console.error('Failed to record attempt:', err);
      toast.error('Progress not saved — check your connection');
    });

    // Always navigate regardless of API result
    if (currentIndex < selectedMaterial.flashcards.length - 1) {
      setIsFlipped(false);
      setTimeout(() => setCurrentIndex(currentIndex + 1), 300);
    } else {
      toast.success('Flashcard set completed! Great work! 🎉');
      setSelectedMaterial(null);
      setCurrentIndex(0);
      setIsFlipped(false);
    }
  };

  if (loading) return <DashboardLayout><div className="loading">Loading flashcards...</div></DashboardLayout>;

  return (
    <DashboardLayout>
      <div className="section-header">
        <Layers size={32} color="#6366f1" />
        <div>
          <h1>AI Flashcards</h1>
          <p>Master core concepts through interactive learning</p>
        </div>
      </div>

      {!selectedMaterial ? (
        <div className="materials-selection">
          {user?.role === 'student' && enrolledCourses.length > 0 && (
            <div className="filter-bar">
              <label className="filter-label">Filter by Course:</label>
              <select
                className="filter-select"
                value={selectedCourse}
                onChange={e => setSelectedCourse(e.target.value)}
              >
                <option value="all">All Courses</option>
                {enrolledCourses.map(c => (
                  <option key={c._id} value={c._id}>{c.subject} — {c.teacherName}</option>
                ))}
              </select>
            </div>
          )}
          {filteredMaterials.length > 0 ? (
            <div className="selection-grid">
              {filteredMaterials.map(m => (
                <div key={m._id} className="selection-card card clickable" onClick={() => setSelectedMaterial(m)}>
                  <div>
                    {user?.role === 'student' && getCourseLabel(m.teacher) && (
                      <span className="course-badge">{getCourseLabel(m.teacher)}</span>
                    )}
                    <h3>{m.title}</h3>
                    <p>{m.flashcards.length} cards generated by AI</p>
                  </div>
                  <ChevronRight size={20} />
                </div>
              ))}
            </div>
          ) : (
            <div className="empty-state card">
              <Sparkles size={48} color="#8b5cf6" />
              <h3>No Flashcards Yet</h3>
              <p>Upload course materials in the "Course Materials" section to generate flashcards automatically.</p>
            </div>
          )}
        </div>
      ) : (
        <div className="flashcard-viewer animate-fade-in">
          <div className="viewer-header">
            <button className="back-btn" onClick={() => setSelectedMaterial(null)}>
              <ChevronLeft size={20} /> Back to Library
            </button>
            <span className="progress">Card {currentIndex + 1} of {selectedMaterial.flashcards.length}</span>
          </div>

          <div className={`flashcard ${isFlipped ? 'flipped' : ''}`} onClick={() => setIsFlipped(!isFlipped)}>
            <div className="card-face front">
              <div className="card-label">FRONT</div>
              <div className="card-content">{selectedMaterial.flashcards[currentIndex].front}</div>
              <div className="card-hint">Click to flip</div>
            </div>
            <div className="card-face back">
              <div className="card-label">BACK</div>
              <div className="card-content">{selectedMaterial.flashcards[currentIndex].back}</div>
              <div className="card-hint">Click to flip back</div>
            </div>
          </div>

          <div className="card-actions">
            <button className="action-btn wrong" onClick={(e) => { e.stopPropagation(); handleRecord(false); }}>
              <XCircle size={24} /> Still Learning
            </button>
            <button className="action-btn correct" onClick={(e) => { e.stopPropagation(); handleRecord(true); }}>
              <CheckCircle2 size={24} /> Got It!
            </button>
          </div>
        </div>
      )}

      <style>{`
        .section-header {
          display: flex;
          align-items: center;
          gap: 16px;
          margin-bottom: 40px;
        }
        .filter-bar {
          display: flex;
          align-items: center;
          gap: 12px;
          margin-bottom: 24px;
        }
        .filter-label {
          font-size: 14px;
          font-weight: 600;
          color: var(--text-muted);
          white-space: nowrap;
        }
        .filter-select {
          padding: 10px 16px;
          border: 1.5px solid var(--border);
          border-radius: var(--radius-md);
          background: var(--bg-card);
          color: var(--text-main);
          font-size: 14px;
          font-weight: 500;
          cursor: pointer;
          min-width: 260px;
        }
        .filter-select:focus { outline: none; border-color: var(--primary); }
        .course-badge {
          display: inline-block;
          background: var(--primary-light);
          color: var(--primary);
          font-size: 11px;
          font-weight: 700;
          padding: 2px 8px;
          border-radius: 20px;
          text-transform: uppercase;
          letter-spacing: 0.4px;
          margin-bottom: 6px;
        }
        .selection-grid {
          display: grid;
          grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
          gap: 20px;
        }
        .selection-card {
          display: flex;
          align-items: center;
          justify-content: space-between;
          padding: 24px;
        }
        .selection-card h3 {
          font-size: 18px;
          margin-bottom: 4px;
        }
        .selection-card p {
          font-size: 14px;
          color: var(--text-muted);
          margin-top: 4px;
        }
        .empty-state {
          text-align: center;
          padding: 60px;
          display: flex;
          flex-direction: column;
          align-items: center;
          gap: 16px;
        }
        .flashcard-viewer {
          max-width: 600px;
          margin: 0 auto;
        }
        .viewer-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 24px;
        }
        .back-btn {
          background: transparent;
          display: flex;
          align-items: center;
          gap: 4px;
          color: var(--text-muted);
          font-weight: 500;
        }
        .progress {
          font-weight: 600;
          color: var(--primary);
          background: var(--primary-light);
          padding: 4px 12px;
          border-radius: 20px;
          font-size: 14px;
        }
        .flashcard {
          width: 100%;
          height: 350px;
          perspective: 1000px;
          cursor: pointer;
          position: relative;
        }
        .card-face {
          position: absolute;
          width: 100%;
          height: 100%;
          backface-visibility: hidden;
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          padding: 40px;
          border-radius: var(--radius-lg);
          box-shadow: var(--shadow-lg);
          border: 1px solid var(--border);
          transition: transform 0.6s cubic-bezier(0.4, 0, 0.2, 1);
          text-align: center;
          background: var(--bg-card);
        }
        .card-label {
          position: absolute;
          top: 20px;
          font-size: 12px;
          font-weight: 800;
          letter-spacing: 1px;
          color: var(--text-muted);
        }
        .card-content {
          font-size: 22px;
          font-weight: 600;
          color: var(--text-main);
          font-family: 'Outfit', sans-serif;
        }
        .card-hint {
          position: absolute;
          bottom: 20px;
          font-size: 12px;
          color: var(--text-muted);
        }
        .front {
          z-index: 2;
        }
        .back {
          transform: rotateY(180deg);
        }
        .flipped .front {
          transform: rotateY(180deg);
        }
        .flipped .back {
          transform: rotateY(360deg);
        }
        .card-actions {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 20px;
          margin-top: 40px;
        }
        .action-btn {
          display: flex;
          align-items: center;
          justify-content: center;
          gap: 12px;
          padding: 16px;
          border-radius: var(--radius-md);
          font-weight: 700;
          transition: var(--transition);
        }
        .action-btn.wrong {
          background: rgba(239,68,68,0.1);
          color: #e11d48;
          border: 1px solid rgba(239,68,68,0.25);
        }
        .action-btn.wrong:hover {
          background: #ffe4e6;
          transform: translateY(-2px);
        }
        .action-btn.correct {
          background: rgba(16,185,129,0.12);
          color: #16a34a;
          border: 1px solid rgba(16,185,129,0.25);
        }
        .action-btn.correct:hover {
          background: rgba(16,185,129,0.2);
          transform: translateY(-2px);
        }
      `}</style>
    </DashboardLayout>
  );
};

export default Flashcards;
